# Generated by Django 5.0.14 on 2025-04-19 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appLogin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='M_Usuario',
        ),
    ]
